#pragma config(Sensor, dgtl4,  Bumper,         sensorDigitalIn)
#pragma config(Motor,  port1,           rightMotor,    tmotorVex393_HBridge, openLoop, reversed, driveRight)
#pragma config(Motor,  port10,          leftMotor,     tmotorVex393_HBridge, openLoop, reversed, driveLeft)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

float Pressed;

task main(){

Pressed = SensorValue[dgtl4];

while(Pressed == 1){
	startMotor(leftMotor,127);
	startMotor(rightMotor,127);
	Pressed = SensorValue[dgtl4];
}

stopMotor(leftMotor);
stopMotor(rightMotor);


}
