#pragma config(Sensor, dgtl4,  Bumper,         sensorDigitalIn)
#pragma config(Sensor, dgtl10, sonarSensor,    sensorSONAR_inch)
#pragma config(Motor,  port1,           rightMotor,    tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port10,          leftMotor,     tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

float Distance;
float Pressed;
bool Button;

task main()
{
	Button = false;
Distance = SensorValue[sonarSensor];
Pressed = SensorValue[dgtl4];
	while(Button == false)
	{
		Pressed = SensorValue[dgtl4];
		if(Pressed == 0){
			Button = true;
	}
		if( Distance < 4  && Distance != -1){
		motor[rightMotor] = -63;
		motor[leftMotor]  = -63;
}
else if( Distance <6  && Distance != -1){
		motor[rightMotor] = 0;
		motor[leftMotor]  = 0;
}
else{
	motor[rightMotor] = 63;
		motor[leftMotor]  = 63;
}

Distance = SensorValue[sonarSensor];

		}

}
