#pragma config(Sensor, dgtl10, sonarSensor,    sensorSONAR_inch)
#pragma config(Motor,  port1,           rightMotor,    tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port10,          leftMotor,     tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

float Distance;

task main()
{
Distance = SensorValue[sonarSensor];

	while( Distance > 6  || Distance == -1)
	{
		motor[rightMotor] = 63;
		motor[leftMotor]  = 63;
	Distance = SensorValue[sonarSensor];

		}

}
