#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           Right,         tmotorVex393_HBridge, openLoop, reversed, driveRight, encoderPort, I2C_1)
#pragma config(Motor,  port10,          Left,          tmotorVex393_HBridge, openLoop, reversed, driveLeft, encoderPort, I2C_2)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
/*hello friend, something is up with the encoders... positions not updating... not sure why... */
float currPos1;
float currPos2;
	float setpoint;
float inches;
float rotate;
float Kp;
float Ki;
float Kd;
float sum1;
float sum2;
float lastError1;
float lastError2;
float error1;
float error2;
float dif1;
float dif2;
float motorOutput1;

float motorOutput2;



task main()
{
/*1: comment out first motor output equals lines = nothing
//2: see why we switch motor Output1 and 2 = nothing
//3: and try just using one to see if that works also*/

while (true){

currPos1 = -SensorValue[I2C_1]+5;
currPos2 = -SensorValue[I2C_1];

rotate = 52.01470588;
inches = 70;

setpoint = rotate * inches;
	Kp = 0.05;
Ki = 0;
	/*Good Ki: 0.000005; */
	Kd = 0.05;
	lastError1 = 0;
		lastError2 = 0;

	error1 = setpoint - currPos1;
	error2 = setpoint - currPos2;

	dif1 = error1 - lastError1;
	dif2 = error2 - lastError2;

		sum1+=error1;
			sum2+=error2;

	motorOutput1 = Kp*error1 + Ki*sum1 + Kd*dif1;
	motorOutput2 = Kp*error2 + Ki*sum2 + Kd*dif2;

	if (motorOutput1 > 127){
		motorOutput1 = 127;
		}
			else if(motorOutput1 < -127){
		motorOutput1 = -127;
		}
if(motorOutput2 > 127){
		motorOutput2 = 127;
	}
	else if(motorOutput2 < -127){
		motorOutput2 = -127;
		}

	motor[Right] = motorOutput1;
	motor[Left] = motorOutput2;

	lastError1 = error1;
	lastError2 = error2;


}



}
