#pragma config(Motor,  port1,           rightDrive,    tmotorVex393_HBridge, openLoop, reversed, driveRight)
#pragma config(Motor,  port10,          leftDrive,     tmotorVex393_HBridge, openLoop, reversed, driveLeft)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

float gain = 0.8;
float throttle;
float turn;
float tempLeft;
float tempRight;
float leftMotor;
float rightMotor;

float skim(float f){
	/*if(f>127) return - (f - 127);
	else if (f < -127) return -(f + 127);
	else return 0;*/
	if (f > 127) return - (f - 127) * gain;
	else if (f < -127) return - (f + 127) * gain;
	else return 0;
}

int threshold = 5;

task main(){
	while(true){
		throttle = vexRT[Ch3];
		turn = vexRT[Ch1];

		if (throttle < threshold && throttle > -threshold) throttle = 0;
		if (turn < threshold && turn > -threshold) turn = 0;

		tempLeft = throttle + turn;
		tempRight = throttle - turn;

		leftMotor = tempLeft + skim(tempRight);
		rightMotor = tempRight + skim(tempLeft);

		motor[leftDrive] = leftMotor;
		motor[rightDrive] = rightMotor;
}
}
